
type: section
title: Gunshot Detector Proxy Configuration
settings:
  network:
    type: section
    title: Networking
    on_edit: sudo systemctl restart gunshot_network_config.service
    settings:
      autoconf:
        type: select
        label: Autoconfiguration
        options:
          none: Use Static IP
          any: Use any available method (DHCP + BOOTP + RARP)
          dhcp: Use DHCP only.
          bootp: Use BOOTP only.
          rarp: Use RARP only.
        default: any
      hostname:
        type: text
        label: Hostname
      client_ip:
        type: text
        label: IP Address
        hint: (Static IP or Fallback)
      netmask:
        type: text
        label: Subnet Mask
      gw_ip:
        type: text
        label: Default Gateway
      dns0_ip:
        type: text
        label: Primary DNS
      dns1_ip:
        type: text
        label: Secondary DNS
      ntp0_ip:
        type: text
        label: NTP Server
  events:
    type: section
    title: Event Types
    on_edit:
      - sudo systemctl restart gunshot@event.service
      - sudo systemctl restart gunshot@onvif_ptz.service
      - sudo systemctl restart gunshot@onvif_relay.service
      - sudo systemctl restart gunshot@rcp_ptz.service
    settings:
      gunshot:
        type: checkbox
        label: gunshot
        default: true
      non-gunshot:
        type: checkbox
        label: non-gunshot
        default: true
  mqtt:
    type: section
    title: MQTT Broker Settings
    on_edit:
      - sudo systemctl restart gunshot@event.service
      - sudo systemctl restart gunshot@senseit_server.service
      - sudo systemctl restart gunshot@senseit_client.service
      - sudo systemctl restart gunshot@detector.service
      - sudo systemctl restart gunshot@onvif_ptz.service
      - sudo systemctl restart gunshot@onvif_relay.service
      - sudo systemctl restart gunshot@rcp_ptz.service
      - sudo systemctl restart gunshot@versatile.service
    settings:
      server:
        type: section
        title: Server
        settings:
          host:
            type: text
            label: Host
            default: 127.0.0.1
            hint: IP or Hostname
          port:
            type: number
            label: Port
            default: 1883
            hint: (usually 1883)
      topics:
        type: section
        title: Topics
        settings:
          evt_all:
            type: text
            label: All Events (JSON)
            default: sentri/detector/event/all
          evt_alarm:
            type: text
            label: Alarm Events (JSON)
            default: sentri/detector/event/alarm
          evt_raw:
            type: text
            label: Raw Event Data
            default: sentri/detector/event/raw
          cmd_raw:
            type: text
            label: Raw Commands
            default: sentri/detector/command/raw
  senseit_server:
    type: section
    title: SenseIT Server
    on_edit: sudo systemctl restart gunshot@senseit_server.service
    settings:
      enable:
        type: checkbox
        label: Enable SenseIT Server
        # default: true
      bind:
        type: text
        label: Bind
        hint: Local IP + Port (blank for auto)
        default: :10001
      conn:
        type: text
        label: Connect
        hint: Remote IP + Port (blank for auto)
        default: :10002
  senseit_client:
    type: section
    title: SenseIT Client
    on_edit: sudo systemctl restart gunshot@senseit_client.service
    settings:
      enable:
        type: checkbox
        label: Enable SenseIT Client
        # default: true
      bind:
        type: text
        label: Listen
        hint: Local IP + Port (blank for auto)
        default: :10004
  detector:
    type: section
    title: Detector
    on_edit: sudo systemctl restart gunshot@detector.service
    settings:
      enable:
        type: checkbox
        label: Enable Detector
        # default: true
      bind:
        type: text
        label: Listen
        hint: Local IP + Port (blank for auto)
        default: :10002
  onvif:
    type: section
    title: ONVIF Camera Control
    settings:
      conn:
        type: text
        label: ONVIF URL
        hint: http://user@pass:camera.example
        on_edit:
          - sudo systemctl restart gunshot@onvif_ptz.service
          - sudo systemctl restart gunshot@onvif_relay.service
      ptz:
        type: section
        title: PTZ
        on_edit: sudo systemctl restart gunshot@onvif_ptz.service
        settings:
          enable:
            type: checkbox
            label: Enable ONVIF PTZ
            # default: true
          az_min:
            type: number
            label: Azimuth Min
            default: -180
          az_max:
            type: number
            label: Azimuth Max
            default: 180
          az_off:
            type: number
            label: Azimuth Offset
            default: 0
          el_min:
            type: number
            label: Elevation Min
            default: 0
          el_max:
            type: number
            label: Elevation Max
            default: 90
          el_off:
            type: number
            label: Elevation Offset
            default: 0
          z_min:
            type: number
            label: Zoom Min
            default: 0
          z_max:
            type: number
            label: Zoom Max
            default: 1
          z_off:
            type: number
            label: Zoom Offset
            default: 0
      relay:
        type: section
        title: Relay Alarm
        on_edit: sudo systemctl restart gunshot@onvif_relay.service
        settings:
          enable:
            type: checkbox
            label: Enable ONVIF Relay
            # default: true
          type:
            type: select
            label: Identifier Type
            options:
              number: Relay Number (specify ID as a number)
              token: Relay Token (specify ID as a string)
            default: token
          id:
            type: text
            label: Relay Identifier
          mode:
            type: select
            label: Mode
            options:
              Monostable: Monostable
              Bistable: Bistable
            default: Monostable
          time:
            type: number
            label: Activation Time
            hint: seconds
            default: 2
          idle:
            type: select
            label: Idle State
            options:
              open: Open
              closed: Closed
            default: open
  rcp_ptz:
    type: section
    title: RCP PTZ
    on_edit: sudo systemctl restart gunshot@rcp_ptz.service
    settings:
      enable:
        type: checkbox
        label: Enable RCP PTZ
        # default: true
      url:
        type: text
        label: URL
        hint: e.g. http://username@password:mycamera.mydomain/rcp.xml
        # default: http://10.0.2.3/rcp.xml
      limits:
        type: section
        title: Limits
        settings:
          az_off:
            type: number
            label: Azimuth Offset
            default: 0
          az_flip:
            type: checkbox
            label: Azimuth Flip
            default: false
          el_off:
            type: number
            label: Elevation Offset
            default: 0
          z_off:
            type: number
            label: Zoom Offset
            default: 0
  versatile:
    type: section
    title: Versatile Packet Output
    on_edit: sudo systemctl restart gunshot@versatile.service
    descr: |
      Availible Substitutions:
        {s}: seconds
        {p}: psc
    settings:
      enable:
        type: checkbox
        label: Enable Versatile Packet Output
      bind:
        type: text
        label: Bind
        hint: Local IP + Port (blank for auto)
      conn:
        type: text
        label: Connect
        hint: Remote IP + Port (blank for auto)
      template:
        type: blocktext
        label: Template
