#!/bin/bash
set -x

# Create system user to run the gunshot services
useradd gunshot --system --no-create-home --user-group

# Create admin user with default pass "password", for authenticating from the webpage and performing actions
useradd admin \
  --no-create-home \
  --password '$6$31q0e/npvu5yXPlc$T/M2RqBuQ.FGro.QmW/ku.cBfOzfcLI4rOHosee6vMWJcTZOEOjlhWIIR9AKbbWTZn6rrtKvpzRIC86PYfVH/0' \
  --groups gunshot

# Give members of the gunshot group the ability to modify the config files
chown gunshot:gunshot /opt/gunshot/
chown gunshot:gunshot /opt/gunshot/config.yaml
chown gunshot:gunshot /opt/gunshot/config.yaml.old
chmod g+w /opt/gunshot/config.yaml
chmod g+w /opt/gunshot/config.yaml.old

# The version of pip that comes in the rpi's python3-pip package is slightly buggy
# and will fail on some of the requirements.txt packages. Upgrade this first.
echo "skipping python3 -m pip install --upgrade pip"

# install python packages that weren't available as debs
echo "skipping python3 -m pip install -r /opt/gunshot/requirements.txt"

# enable the relevant systemd units
systemctl daemon-reload
systemctl enable gunshot.target

#systemctl enable gunshot_network_config.service

systemctl enable gunshot@event.service
systemctl enable gunshot@senseit_server.service
systemctl enable gunshot@senseit_client.service
systemctl enable gunshot@detector.service
systemctl enable gunshot@onvif_ptz.service
systemctl enable gunshot@onvif_relay.service
systemctl enable gunshot@rcp_ptz.service
systemctl enable gunshot@versatile.service

systemctl restart gunshot@event.service
systemctl restart gunshot@senseit_server.service
systemctl restart gunshot@senseit_client.service
systemctl restart gunshot@detector.service
systemctl restart gunshot@onvif_ptz.service
systemctl restart gunshot@onvif_relay.service
systemctl restart gunshot@rcp_ptz.service
systemctl restart gunshot@versatile.service

systemctl reload nginx